"""create requests table

Revision ID: 45fe502e05cf
Revises: a7dd8850c1a8
Create Date: 2025-05-26 19:50:15.463606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fe502e05cf'
down_revision: Union[str, None] = 'a7dd8850c1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_up_x', sa.Float(), nullable=False),
    sa.Column('pick_up_y', sa.Float(), nullable=False),
    sa.Column('drop_off_x', sa.Float(), nullable=False),
    sa.Column('drop_off_y', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
